/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Süreç ayakta mı? (liveness)
         * @description LIVENESS: yalnızca sürecin yaşadığını söyler.
         *
         *     Bilinçli olarak hiçbir bağımlılığı kontrol etmez. Aksi halde LLM
         *     geçici olarak düştüğünde orkestratör (Docker/Kubernetes) sağlıklı
         *     bir süreci gereksizce yeniden başlatır.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Trafik alabilir mi? (readiness)
         * @description READINESS: modeller yüklü ve index dolu mu?
         */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Soru sor (kaynak gösteren cevap)
         * @description NOT `async def` — bilinçli.
         *     Model çıkarımı bloklayan bir iştir; `async def` içinde yapılırsa olay
         *     döngüsünü kilitler ve tüm sunucu tek soru boyunca durur. Senkron
         *     tanımlandığında FastAPI bunu iş parçacığı havuzunda çalıştırır.
         */
        post: operations["ask_ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ask/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Soru sor (token token akış)
         * @description Server-Sent Events ile akış.
         *
         *     Toplam süre aynı olsa bile ilk token'ın erken gelmesi algılanan hızı
         *     belirgin değiştirir. Atıf doğrulama akış sonrası yapılabilir; akış
         *     sırasında metnin tamamı henüz yoktur.
         */
        post: operations["ask_stream_ask_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Kütüphanedeki dokümanları listele */
        get: operations["list_documents_documents_get"];
        put?: never;
        /**
         * Doküman yükle (ve isteğe bağlı indeksle)
         * @description Dosyayı yükle, isteğe bağlı olarak hemen indeksle.
         *
         *     AKIŞ HALİNDE OKUMA: dosya belleğe TOPTAN alınmıyor. 8 KB'lık
         *     bloklar hâlinde okunup diske yazılıyor ve bayt sayısı yazarken
         *     sayılıyor. `Content-Length` başlığına güvenilmez — istemci yalan
         *     söyleyebilir; sınır gerçek yazılan bayta göre uygulanır.
         *
         *     `index=True` (varsayılan): yükleme sonrası indeksleme senkron
         *     çalışır. Kullanıcı sonucu ANINDA öğrenir — dosya aranabilir mi,
         *     yoksa taranmış olduğu için OCR mı gerekiyor? Arka plan görevine
         *     atsaydık istemci "yüklendi" cevabını alır ama dosyanın işe yarayıp
         *     yaramadığını bilemezdi.
         */
        post: operations["upload_document_documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{file_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Dokümanı ve chunk'larını sil
         * @description Dokümanı index'ten, manifest'ten ve diskten siler.
         *
         *     Üçü birden yapılmazsa sistem tutarsız kalır: silinmiş bir
         *     dokümandan alıntı yapan cevaplar üretilir ve kullanıcı kaynağı
         *     bulamaz.
         */
        delete: operations["delete_document_documents__file_name__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * data/raw klasörünü indeksle
         * @description Kaynak klasörü indeksle (idempotent).
         *
         *     Değişmemiş dosyalar atlanır. `force=true` ile tümü yeniden işlenir —
         *     chunk ayarları değiştiğinde gerekir, çünkü bu değişiklik dosya
         *     içeriğine yansımaz ve hash aynı kalır.
         */
        post: operations["ingest_ingest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AskRequest
         * @description Soru isteği.
         */
        AskRequest: {
            /**
             * Question
             * @description Dokümanlara sorulacak soru
             * @example SmartSafe AI hangi sektöre yönelik?
             */
            question: string;
            /** Top K */
            top_k?: number | null;
        };
        /**
         * AskResponse
         * @description Soru cevabı ve onu denetlenebilir kılan bilgiler.
         */
        AskResponse: {
            /** Question */
            question: string;
            /** Answer */
            answer: string;
            /**
             * Abstained
             * @description Model bilgi olmadığını mı söyledi?
             */
            abstained: boolean;
            /**
             * Grounded
             * @description Cevap ya atıflı ya da bilinçli çekimser mi?
             */
            grounded: boolean;
            /** Citations */
            citations: components["schemas"]["CitationOut"][];
            /** Sources */
            sources: components["schemas"]["SourceOut"][];
            /** Groundedness */
            groundedness?: number | null;
            /** Model */
            model: string;
            /** Prompt Version */
            prompt_version: string;
            /** Latency Ms */
            latency_ms: number;
        };
        /** Body_upload_document_documents_post */
        Body_upload_document_documents_post: {
            /**
             * File
             * @description PDF dosyası
             */
            file: string;
            /**
             * Index
             * @default true
             */
            index: boolean;
            /**
             * Overwrite
             * @default false
             */
            overwrite: boolean;
        };
        /**
         * CitationOut
         * @description Cevaptaki bir atıf.
         */
        CitationOut: {
            /** Marker */
            marker: number;
            /**
             * Source
             * @description İnsan tarafından okunabilir kaynak etiketi
             */
            source: string;
            /**
             * Chunk Id
             * @description Dayanak chunk'ın kimliği (izlenebilirlik)
             */
            chunk_id: string;
        };
        /** ComponentHealth */
        ComponentHealth: {
            /** Name */
            name: string;
            /** Ok */
            ok: boolean;
            /** Detail */
            detail: string;
        };
        /** DeleteResponse */
        DeleteResponse: {
            /** File Name */
            file_name: string;
            /** Removed Chunks */
            removed_chunks: number;
            /** Index Vectors */
            index_vectors: number;
        };
        /** DocumentListResponse */
        DocumentListResponse: {
            /** Documents */
            documents: components["schemas"]["DocumentOut"][];
            /** Total */
            total: number;
            /**
             * Searchable
             * @description Aramaya gerçekten dahil olan doküman sayısı
             */
            searchable: number;
            /** Needs Ocr */
            needs_ocr: number;
            /** Index Vectors */
            index_vectors: number;
            /** Disk Usage Bytes */
            disk_usage_bytes: number;
        };
        /**
         * DocumentOut
         * @description Kütüphanedeki bir doküman.
         */
        DocumentOut: {
            /** File Name */
            file_name: string;
            /** Status */
            status: string;
            /** Size Bytes */
            size_bytes: number;
            /** Page Count */
            page_count: number;
            /** Chunk Count */
            chunk_count: number;
            /**
             * Is Searchable
             * @description Aramaya dahil mi? (0 chunk = hayır)
             */
            is_searchable: boolean;
            /**
             * Needs Ocr
             * @description Taranmış PDF — OCR gerekiyor
             */
            needs_ocr: boolean;
            /** Processed At */
            processed_at?: string | null;
            /** Error */
            error?: string | null;
        };
        /** DocumentReportOut */
        DocumentReportOut: {
            /** File Name */
            file_name: string;
            /** Status */
            status: string;
            /** Page Count */
            page_count: number;
            /** Chunk Count */
            chunk_count: number;
            /** Error */
            error?: string | null;
            /** Needs Ocr */
            needs_ocr: boolean;
        };
        /**
         * ErrorResponse
         * @description Tek biçimli hata cevabı.
         *
         *     `detail` istemciye gösterilebilir bir açıklama içerir; yığın izi (stack
         *     trace) ASLA dışarı verilmez — dosya yolları ve iç yapı sızdırır.
         */
        ErrorResponse: {
            /**
             * Error
             * @description Makine tarafından okunabilir hata kodu
             */
            error: string;
            /**
             * Detail
             * @description İnsan tarafından okunabilir açıklama
             */
            detail: string;
            /** Request Id */
            request_id?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Hazırlık (readiness) durumu.
         *
         *     LIVENESS ile READINESS AYRIMI:
         *       * liveness  → süreç ayakta mı? (yeniden başlatılmalı mı?)
         *       * readiness → trafik alabilir mi? (modeller yüklü, index dolu mu?)
         *       İkisini karıştırmak, model yüklenirken gelen isteklerin hata almasına
         *       veya sağlıklı bir sürecin gereksiz yeniden başlatılmasına yol açar.
         */
        HealthResponse: {
            /** Ready */
            ready: boolean;
            /** Components */
            components: components["schemas"]["ComponentHealth"][];
            /** Index Vectors */
            index_vectors: number;
            /** Embedder Model */
            embedder_model: string;
            /** Llm Model */
            llm_model: string;
            /** Retrieval Strategy */
            retrieval_strategy: string;
        };
        /**
         * IngestRequest
         * @description Yeniden indeksleme isteği.
         */
        IngestRequest: {
            /**
             * Force
             * @description Idempotency kontrolünü atla. Chunk ayarları veya normalizasyon mantığı değiştiğinde gerekir: bunlar dosya içeriğine yansımadığı için hash aynı kalır ve dosya normalde atlanır.
             * @default false
             */
            force: boolean;
        };
        /** IngestResponse */
        IngestResponse: {
            /** Documents */
            documents: components["schemas"]["DocumentReportOut"][];
            /** Chunks Added */
            chunks_added: number;
            /** Index Total */
            index_total: number;
            /** Duration Seconds */
            duration_seconds: number;
            /** Failed Count */
            failed_count: number;
            /** Needs Ocr Count */
            needs_ocr_count: number;
        };
        /**
         * SourceOut
         * @description Cevapta kullanılan bir bağlam parçası.
         */
        SourceOut: {
            /** Marker */
            marker: number;
            /** Source */
            source: string;
            /** Chunk Id */
            chunk_id: string;
            /** Score */
            score: number;
            /**
             * Retriever Hits
             * @description Kaç retriever bu parçayı buldu (1'den büyükse uzlaşma var)
             */
            retriever_hits: number;
            /**
             * Preview
             * @description Metnin ilk kısmı — tam metin dönmez
             */
            preview: string;
        };
        /**
         * UploadResponse
         * @description Yükleme sonucu.
         */
        UploadResponse: {
            /**
             * File Name
             * @description Sunucunun kaydettiği TEMİZLENMİŞ ad
             */
            file_name: string;
            /** Size Bytes */
            size_bytes: number;
            /**
             * Indexed
             * @description Yükleme sonrası indeksleme yapıldı mı
             */
            indexed: boolean;
            /**
             * Chunk Count
             * @default 0
             */
            chunk_count: number;
            /** Status */
            status: string;
            /**
             * Needs Ocr
             * @default false
             */
            needs_ocr: boolean;
            /** Duplicate Of */
            duplicate_of?: string | null;
            /** Warning */
            warning?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    ask_ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    ask_stream_ask_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_documents_documents_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentListResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    upload_document_documents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_document_documents_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    delete_document_documents__file_name__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                file_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    ingest_ingest_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
